project:
  type: website
  output-dir: docs

website:
  title: "Haikoo Khandor"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: papers
        text: Publications
      - href: news.qmd
        text: News
      - href: teaching.qmd
        text: Teaching
  
    
    

format:
  html:
    theme:
      light: [litera, styles.scss]
      dark: [darkly, styles-dark.scss]
    highlight-style: a11y-dark
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto

